Bad code -> Good code
Atharv-Agarwal/cord pull request #1
Opened 2021-12-11 06:11 UTC by Sibi-Agilan

2021-12-11 13:05 UTC, Atharv-Agarwal commented
Honestly I dont like the 3rd commit, starts with is not a great way to manage code

2021-12-13 03:42 UTC, Sibi-Agilan commented
Lots of small commands are the bad way to code with dpy, it takes around 0.2 to 0.3 seconds to register a command. The startswith method is used to shorten the code and makes it much more readable. Repeating a block of code more than once in python means you're doing something wrong. Try to implement the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle in your code.

2021-12-13 09:15 UTC, Atharv-Agarwal submitted a review, later dismissed

2021-12-13 09:20 UTC, Atharv-Agarwal requested changes

2021-12-13 09:20 UTC, Atharv-Agarwal commented on autoreact/autoreact.py
> +				return
Should there be a extra indent here?

2021-12-13 09:37 UTC, Atharv-Agarwal requested changes
This needs to be undone since the way my hosting manages the bot is it reboots it when it crashes. Therefore client.close() acts as a way to reboot. Deprecation warning has been fixed as per #2

2021-12-14 04:26 UTC, Sibi-Agilan commented on autoreact/autoreact.py
> +				return
Its not needed, my mistake

2021-12-14 05:39 UTC, Atharv-Agarwal commented on autoreact/autoreact.py
> +				return
Could you fix those so I can accept this PR? Thanks for helping

2021-12-14 06:09 UTC, Atharv-Agarwal commented on discordyt/discordyt.py
> +		self.client = client
Could you convert this to bot please

2021-12-14 06:12 UTC, Atharv-Agarwal commented on extras/extras.py
> +			f"``` {msg.embeds[0].description} ```" if msg and msg.embeds else "Please provide a valid message link / "
This takes int as a input i.e message ID. Could you change this to say "Please provide a valid message ID."

2021-12-14 06:14 UTC, Atharv-Agarwal commented on newcomers/newcomers.py
> +def to_seconds(s):
Should the definition be outside the class?

2021-12-14 06:16 UTC, Atharv-Agarwal commented on premiumsupport/premiumsupport.py
> +            await thread.send(Msg, destination=recipient, from_mod=True, anonymous=True)
This has been updated in the base to check for msg and ping, please update this

2021-12-14 06:17 UTC, Atharv-Agarwal commented on snipe/snipe.py
> +def check_view_perms(channel, member):
Again, should the definition be outside the class?

2021-12-14 06:18 UTC, Atharv-Agarwal requested changes
If you could do the changes requested and clarify I can merge this!

2021-12-14 06:43 UTC, Sibi-Agilan commented on premiumsupport/premiumsupport.py
> +            await thread.send(Msg, destination=recipient, from_mod=True, anonymous=True)
Done

2021-12-14 07:28 UTC, merged

2021-12-14 07:42 UTC, Atharv-Agarwal commented
Code broke :(( 
Bfping.py
`if message.author.bot or not message.channel.permissions_for(message.author, discord.Permissions.manage_messages):
TypeError: permissions_for() takes 2 positional arguments but 3 were given` ( Reverted)

extras.py raw was a static method and ctx.send doesnt work. (Reverted)